% 'JHU-ICBM_WM_tract_prob_1mm' or 'HO_subcortical_1mm'

% --== Tries ==--
% 65to75 + HO_subcortical_1mm
% 65to75 + JHU-ICBM_WM_tract_prob_1mm
% 70to80 + HO_subcortical_1mm
% 70to80 + JHU-ICBM_WM_tract_prob_1mm
% creating + HO_subcortical_1mm

% UBO Detector version TOPMAL
TOPMAL_UDver ('/data_pri/jiyang/OW3_WMH_20170721', ...
               'creating template', ...
               'NA', ...
               '/usr/share/spm12', ...
               'HO_subcortical_1mm', ...
               '')


           
% Generic version TOPMAL
% TOPMAL_generic (DARles_folder, ...
%                 study_folder, ...
%                 DARtem, ...
%                 ageRange, ...
%                 spm12path, ...
%                 atlasCode)