
clc;

addpath ('/home/jiyang/Dropbox/Jiyang/CNSP/CNS/WMH_extraction/WMHextraction_long');

WMHextraction_long_paired ('/data_pri/jiyang/wmhProject/workingData/MAS/MAS_tp123_forPaper_cheating_TP2asTP1', ...
3, ...
'/usr/share/spm12', ...
'existing template', ...
5, ...
'12', ...
'', ...
'', ...
'built-in', ...
'65to75', ...
0.7, ...
'web' ...
)