function model = build_kNN_classifier (NumNeighbors, feature4training, decision4training, trainingFeatures1, varargin)

features = importdata (feature4training);
decision = importdata (decision4training);

% model = fitcknn (features, decision, ...
%                 'NumNeighbors', NumNeighbors, ...
%                 'Standardize', 1);

% intensity-only kNN (i.e. first kNN)
if nargin == 4
    model = fitcknn (features(:,trainingFeatures1), decision, ...
                    'NumNeighbors', NumNeighbors, ...
                    'Standardize', 1);
elseif nargin > 4
    model = fitcknn (features(:,trainingFeatures1), decision, ...
                    'NumNeighbors', NumNeighbors, ...
                    varargin{:} ...
                    );  
end
