%%%% an example %%%%
operationFolder = '/data_pub/jiyang/UBO_Detector_leave-one-out';
completeFeatureFile = '/data_pub/jiyang/UBO_Detector_leave-one-out/RUN_predicting0099/customiseClassifier/textfiles/feature_forTraining.txt';
completeDecisionFile = '/data_pub/jiyang/UBO_Detector_leave-one-out/RUN_predicting0099/customiseClassifier/textfiles/decision_forTraining.txt';
completeLookupFile = '/data_pub/jiyang/UBO_Detector_leave-one-out/RUN_predicting0099/customiseClassifier/textfiles/lookup_forTraining.txt';
spm12path = '/usr/share/spm12';
k = 9;
ageRange = '70to80';
probThr = 0.9;
groundTruth_folder = '/data_pub/jiyang/UBO_Detector_leave-one-out/groundTruth';

LOO_folder = fileparts (mfilename ('fullpath'));
addpath (LOO_folder);

LOO_main (operationFolder, ...
            completeFeatureFile, ...
            completeDecisionFile, ...
            completeLookupFile, ...
            spm12path, ...
            k, ...
            ageRange, ...
            probThr, ...
            groundTruth_folder)
%%%%%%%%%%%%%%%%%%%%