function LOO_runUBOdetector (operationFolder, uniqueIDs_cellArr, spm12path, k, ageRange, probThr)
	LOO_folder = fileparts (mfilename ('fullpath'));
	WMHext_folder = fileparts (LOO_folder);
	WMHext_cmd_folder = [WMHext_folder '/cmd/WMHext'];

	addpath (WMHext_cmd_folder);

	[N_uniqueIDs, ~] = size (uniqueIDs_cellArr);

	for i = 1:N_uniqueIDs
		WMHextraction_woQC_cmd ([operationFolder '/LOO_predict' uniqueIDs_cellArr{i}], ...
	                            spm12path, ...
	                            'existing template', ...
	                            k, ... % integer
	                            '12', ... % string
	                            '', ...
	                            '', ...
	                            'customised', ...
	                            ageRange, ...
	                            probThr, ... % float
	                            'web' ...
	                            )
	end

