%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% generate.m
%
% This function will warp the indicated Dartel template into native space.
% It requires rc(1-3)(subID)_T1.nii to have been created already 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function generate(obj, CNS_path, age_range, studyFolder, subID);
    
    % first setup the required folders
    templateDir = strcat(studyFolder,'/subjects/',subID,'/NativeTemplate');
    mkdir templateDir;

    % this little hack is required for now to get the 
    % DARTEL template into native space
    dtemplate = DartelTemplate(CNS_path, age_range);
    WMHextraction_preprocessing_Step3(studyFolder,CNS_path,dtemplate,'','',ageRange);

    % and move the warp to our template directory
    warpfile = strcat('u_rc1',subID,'_T1.nii')
    movefile strcat(studyFolder,'/subjects/',subID,...
                    '/mri/preprocessing/',warpfile)

    % set our paths ...
    brain_mask = strcat( ...
            CNS_path,'/Templates/DARTEL_brain_mask/', ...
            age_range, '/DARTEL_brain_mask.nii.gz');
    gm_prob = strcat( ...
            CNS_path,'/Templates/DARTEL_GM_WM_CSF_prob_maps/', ...
            age_range,'/DARTEL_GM_prob_map.nii.gz');
    wm_prob = strcat( ...
            CNS_path,'/Templates/DARTEL_GM_WM_CSF_prob_maps/', ...
            age_range,'/DARTEL_WM_prob_map.nii.gz');
    csf_prob = strcat( ...
            CNS_path,'/Templates/DARTEL_GM_WM_CSF_prob_maps/', ...
            age_range,'/DARTEL_CSF_prob_map.nii.gz');
    gm_prob_thr = strcat( ...
            CNS_path,'/Templates/DARTEL_GM_WM_CSF_prob_maps/', ...
            age_range,'/DARTEL_GM_prob_map_thr0_8.nii.gz');
    wm_prob_thr = strcat( ...
            CNS_path,'/Templates/DARTEL_GM_WM_CSF_prob_maps/', ...
            age_range,'/DARTEL_WM_prob_map_thr0_8.nii.gz');
    csf_prob_thr = strcat( ...
            CNS_path,'/Templates/DARTEL_GM_WM_CSF_prob_maps/', ...
            age_range,'/DARTEL_CSF_prob_map_thr0_8.nii.gz');
    ventricles = strcat( ...
            CNS_path,'/Templates/DARTEL_ventricle_distance_map/', ...
            'DARTEL_ventricle_distance_map.nii.gz');
    lobar = strcat( ...
            CNS_path,'/Templates/DARTEL_lobar_and_aterial_/', ...
                'DARTEL_lobar_nii.gz');
    arterial = strcat( ...
            CNS_path,'/Templates/DARTEL_lobar_and_aterial_/', ...
                'DARTEL_arterial_nii.gz');

    % now apply the warp to each of the necessary template files
    CNSP_DARTELtoNative(brain_mask,strcat(templateDir,'/',warpfile)
    CNSP_DARTELtoNative(gm_prob,strcat(templateDir,'/',warpfile)
    CNSP_DARTELtoNative(wm_prob,strcat(templateDir,'/',warpfile)
    CNSP_DARTELtoNative(csf_prob,strcat(templateDir,'/',warpfile)
    CNSP_DARTELtoNative(gm_prob_thr,strcat(templateDir,'/',warpfile)
    CNSP_DARTELtoNative(wm_prob_thr,strcat(templateDir,'/',warpfile)
    CNSP_DARTELtoNative(csf_prob_thr,strcat(templateDir,'/',warpfile)
    CNSP_DARTELtoNative(ventricles,strcat(templateDir,'/',warpfile)
    CNSP_DARTELtoNative(lobar,strcat(templateDir,'/',warpfile)
    CNSP_DARTELtoNative(arterial,strcat(templateDir,'/',warpfile)


