% mode = 'procAndExt' or 'onlyExt'

function ASLprocessing_main_FSL_postproc_arterialTerr (studyFolder, mode)

	Perfusion_folder = fileparts (mfilename ('fullpath'));

	origT1folder = [studyFolder '/originalImg/T1'];

	origT1folder_contents = dir ([origT1folder '/*.nii.gz']);

	Nsubj = size (origT1folder_contents, 1);

	% text output
	system (['if [ -f "' studyFolder '/subjects/CBFinArterialTerritories.txt" ];' ...
				'then rm -f ' studyFolder '/subjects/CBFinArterialTerritories.txt;fi']);

	system (['echo ' '"ID,' ...
					 'ACA_GM,' ...
					 'MCA_GM,' ...
					 'PCA_GM,' ...
					 'ACA_WM,' ...
					 'MCA_WM,' ...
					 'PCA_WM,' ...
					 'ACA_global,' ...
					 'MCA_global,' ...
					 'PCA_global,' ...
					 'right_anterior_artery_hemisphere_GM,' ...
					 'left_anterior_artery_hemisphere_GM,' ...
					 'right_middle_artery_hemisphere_GM,' ...
					 'right_posterior_artery_hemisphere_GM,' ...
					 'left_posterior_artery_hemisphere_GM,' ...
					 'left_middle_artery_hemisphere_GM,' ...
					 'right_anterior_artery_callosal_GM,' ...
					 'left_anterior_artery_callosal_GM,' ...
                     'right_middle_artery_lateral_lenticulostriate_GM,' ...
					 'left_middle_artery_lateral_lenticulostriate_GM,' ...
                     'right_posterior_artery_thalamic_and_midbrain_perforators_GM,' ...
					 'left_posterior_artery_thalamic_and_midbrain_perforators_GM,' ...
					 'right_anterior_artery_medial_lenticulostriate_GM,' ...
					 'left_anterior_artery_medial_lenticulostriate_GM,' ...
					 'right_posterior_artery_callosal_GM,' ...
					 'left_posterior_artery_callosal_GM,' ...
					 'right_anterior_artery_hemisphere_WM,' ...
					 'left_anterior_artery_hemisphere_WM,' ...
					 'right_middle_artery_hemisphere_WM,' ...
					 'right_posterior_artery_hemisphere_WM,' ...
					 'left_posterior_artery_hemisphere_WM,' ...
					 'left_middle_artery_hemisphere_WM,' ...
					 'right_anterior_artery_callosal_WM,' ...
					 'left_anterior_artery_callosal_WM,' ...
                     'right_middle_artery_lateral_lenticulostriate_WM,' ...
					 'left_middle_artery_lateral_lenticulostriate_WM,' ...
                     'right_posterior_artery_thalamic_and_midbrain_perforators_WM,' ...
					 'left_posterior_artery_thalamic_and_midbrain_perforators_WM,' ...
					 'right_anterior_artery_medial_lenticulostriate_WM,' ...
					 'left_anterior_artery_medial_lenticulostriate_WM,' ...
					 'right_posterior_artery_callosal_WM,' ...
					 'left_posterior_artery_callosal_WM,' ...
					 'right_anterior_artery_hemisphere_global,' ...
					 'left_anterior_artery_hemisphere_global,' ...
					 'right_middle_artery_hemisphere_global,' ...
					 'right_posterior_artery_hemisphere_global,' ...
					 'left_posterior_artery_hemisphere_global,' ...
					 'left_middle_artery_hemisphere_global,' ...
					 'right_anterior_artery_callosal_global,' ...
					 'left_anterior_artery_callosal_global,' ...
                     'right_middle_artery_lateral_lenticulostriate_global,' ...
					 'left_middle_artery_lateral_lenticulostriate_global,' ...
                     'right_posterior_artery_thalamic_and_midbrain_perforators_global,' ...
					 'left_posterior_artery_thalamic_and_midbrain_perforators_global,' ...
					 'right_anterior_artery_medial_lenticulostriate_global,' ...
					 'left_anterior_artery_medial_lenticulostriate_global,' ...
					 'right_posterior_artery_callosal_global,' ...
					 'left_posterior_artery_callosal_global' ...
					 '" > ' ...
					 studyFolder '/subjects/CBFinArterialTerritories.txt']);


	% postprocessing - extract arterial territories
	if strcmp (mode, 'procAndExt')
		parfor i = 1:Nsubj

			T1filenameParts = strsplit (origT1folder_contents(i).name, '_');
			ID = T1filenameParts{1};

			system ([Perfusion_folder '/ASLprocessing_FSL/ASLprocessing_FSL_postprocessing_arterialTerr.sh ' ...
													'--Sdir ' studyFolder ' -id ' ID]);

		end
	end

	% write TXT output
	fprintf ('Summarising arterial territories CBF ...');

	for i = 1:Nsubj

		T1filenameParts = strsplit (origT1folder_contents(i).name, '_');
		ID = T1filenameParts{1};

		system ([Perfusion_folder '/ASLprocessing_FSL/ASLprocessing_FSL_postprocessing_arterialTerr_summariseTXToutput.sh ' ...
												'--Sdir ' studyFolder ' -id ' ID]);

	end

	fprintf ('   Done.\n');