% ASLprocessing_main_ASLtbx.m
% example run

% %% test
% studyFolder = '/data_pub/jiyang/ASLprocessing/reconvertedRawData_reprocessing/pCASL_ASLtbx2_csf/test';
% ASLtype = 'pCASL';
% spm12path = '/usr/share/spm12';
% parameters = 'OATS';
% sepM0fromPASLasFirstVol = 'N';
% calib_voxORfixVal = 'voxel';
% calib_wmORcsf = 'CSF';
% procMode = 'wholeProc';

% ASLprocessing_main_ASLtbx (ASLtype, ...
%                            studyFolder, ...
%                            spm12path, ...
%                            parameters, ...
%                            sepM0fromPASLasFirstVol, ...
%                            calib_voxORfixVal, ...
%                            calib_wmORcsf, ...
%                            procMode)






% ================= %
% Formal processing %
% ================= %

basedir = '/data_pub/jiyang/ASLprocessing/reconvertedRawData_reprocessing/ASLtbx2';
procMode = 'wholeProc';

% %% pCASL - voxelM0
% studyFolder = [basedir '/pCASL_ASLtbx2_vox'];
% ASLtype = 'pCASL';
% spm12path = '/usr/share/spm12';
% parameters = 'OATS';
% sepM0fromPASLasFirstVol = 'N';
% calib_voxORfixVal = 'voxel';
% calib_wmORcsf = 'CSF';
% 
% ASLprocessing_main_ASLtbx (ASLtype, ...
%                            studyFolder, ...
%                            spm12path, ...
%                            parameters, ...
%                            sepM0fromPASLasFirstVol, ...
%                            calib_voxORfixVal, ...
%                            calib_wmORcsf, ...
%                            procMode)

                       
%% pCASL - M0csf - fixVal1
studyFolder = [basedir '/pCASL_ASLtbx2_csf_fixVal1'];
ASLtype = 'pCASL';
spm12path = '/usr/share/spm12';
parameters = 'OATS';
sepM0fromPASLasFirstVol = 'N';
calib_voxORfixVal = 'fixVal1';
calib_wmORcsf = 'CSF';

ASLprocessing_main_ASLtbx (ASLtype, ...
                           studyFolder, ...
                           spm12path, ...
                           parameters, ...
                           sepM0fromPASLasFirstVol, ...
                           calib_voxORfixVal, ...
                           calib_wmORcsf, ...
                           procMode)
                       
                       
                       
%% pCASL - M0wm - fixVal1
studyFolder = [basedir '/pCASL_ASLtbx2_wm_fixVal1'];
ASLtype = 'pCASL';
spm12path = '/usr/share/spm12';
parameters = 'OATS';
sepM0fromPASLasFirstVol = 'N';
calib_voxORfixVal = 'fixVal1';
calib_wmORcsf = 'WM';

ASLprocessing_main_ASLtbx (ASLtype, ...
                           studyFolder, ...
                           spm12path, ...
                           parameters, ...
                           sepM0fromPASLasFirstVol, ...
                           calib_voxORfixVal, ...
                           calib_wmORcsf, ...
                           procMode)
                       
                       
%% pCASL - M0wm - fixVal2
studyFolder = [basedir '/pCASL_ASLtbx2_wm_fixVal2'];
ASLtype = 'pCASL';
spm12path = '/usr/share/spm12';
parameters = 'OATS';
sepM0fromPASLasFirstVol = 'N';
calib_voxORfixVal = 'fixVal2';
calib_wmORcsf = 'WM';

ASLprocessing_main_ASLtbx (ASLtype, ...
                           studyFolder, ...
                           spm12path, ...
                           parameters, ...
                           sepM0fromPASLasFirstVol, ...
                           calib_voxORfixVal, ...
                           calib_wmORcsf, ...
                           procMode)
                       
% %% PASL - voxelM0
% studyFolder = [basedir '/PASL_ASLtbx2_vox'];
% ASLtype = 'PASL';
% spm12path = '/usr/share/spm12';
% parameters = 'OATS';
% sepM0fromPASLasFirstVol = 'Y';
% calib_voxORfixVal = 'voxel';
% calib_wmORcsf = 'CSF';
% 
% ASLprocessing_main_ASLtbx (ASLtype, ...
%                            studyFolder, ...
%                            spm12path, ...
%                            parameters, ...
%                            sepM0fromPASLasFirstVol, ...
%                            calib_voxORfixVal, ...
%                            calib_wmORcsf, ...
%                            procMode)
 
%% PASL - M0csf - fixVal1
studyFolder = [basedir '/PASL_ASLtbx2_csf_fixVal1'];
ASLtype = 'PASL';
spm12path = '/usr/share/spm12';
parameters = 'OATS';
sepM0fromPASLasFirstVol = 'Y';
calib_voxORfixVal = 'fixVal1';
calib_wmORcsf = 'CSF';

ASLprocessing_main_ASLtbx (ASLtype, ...
                           studyFolder, ...
                           spm12path, ...
                           parameters, ...
                           sepM0fromPASLasFirstVol, ...
                           calib_voxORfixVal, ...
                           calib_wmORcsf, ...
                           procMode)

%% PASL - M0wm - fixVal1
studyFolder = [basedir '/PASL_ASLtbx2_wm_fixVal1'];
ASLtype = 'PASL';
spm12path = '/usr/share/spm12';
parameters = 'OATS';
sepM0fromPASLasFirstVol = 'Y';
calib_voxORfixVal = 'fixVal1';
calib_wmORcsf = 'WM';

ASLprocessing_main_ASLtbx (ASLtype, ...
                           studyFolder, ...
                           spm12path, ...
                           parameters, ...
                           sepM0fromPASLasFirstVol, ...
                           calib_voxORfixVal, ...
                           calib_wmORcsf, ...
                           procMode)

                       
                       
%% PASL - M0wm - fixVal2
studyFolder = [basedir '/PASL_ASLtbx2_wm_fixVal2'];
ASLtype = 'PASL';
spm12path = '/usr/share/spm12';
parameters = 'OATS';
sepM0fromPASLasFirstVol = 'Y';
calib_voxORfixVal = 'fixVal2';
calib_wmORcsf = 'WM';

ASLprocessing_main_ASLtbx (ASLtype, ...
                           studyFolder, ...
                           spm12path, ...
                           parameters, ...
                           sepM0fromPASLasFirstVol, ...
                           calib_voxORfixVal, ...
                           calib_wmORcsf, ...
                           procMode)
                       
% ===================== %
% end formal processing %
% ===================== %





% %% ASLtbx2 example
% studyFolder = '/data_pub/jiyang/ASLtbx_examples/ASLtbx2/test/test_studyFolder';
% ASLtype = 'PASL';
% spm12path = '/usr/share/spm12';
% parameters = 'ASLtbx2_example';
% sepM0fromPASLasFirstVol = 'N';
% calib_voxORfixVal = 'voxel';
% calib_wmORcsf = 'WM';
% 
% ASLprocessing_main_ASLtbx (ASLtype, ...
%                            studyFolder, ...
%                            spm12path, ...
%                            parameters, ...
%                            sepM0fromPASLasFirstVol, ...
%                            calib_voxORfixVal, ...
%                            calib_wmORcsf)


%                        
%% - asl_perf_subtract run after generating all necessary imgs
%   pCASL run
% ASLtbx_path = '/home/jiyang/Dropbox/Jiyang/CNSP/CNS/Perfusion/ASLtbx2_Jmod';
% spm12path = '/usr/share/spm12';
% addpath (ASLtbx_path, spm12path);
% 
% ID_folder = '/data_pub/jiyang/ASL_testing_pCASL/subjects/11308D';
% 
% Filename = [ID_folder '/imgs4ASLtbx/sASLflt_r11308D_pCASL.nii'];
% FirstimageType = 1;
% SubtractionType = 0;
% SubtractionOrder = 0;
% 
% % using voxel M0
% fixM0 = 1;
% M0wmcsf2estimateM0b = 1;
% 
% Flag = [1 1 1 1 1 1 fixM0 1 1 M0wmcsf2estimateM0b];
% Timeshift = 0.5;
% AslType = 1;
% labeff = 0.85;
% MagType = 1;
% Labeltime = 1.8;
% Delaytime = 2.0;
% Slicetime = 35.3125;
% TE = 12;
% M0img = [ID_folder '/imgs4ASLtbx/sr11308D_M0.nii'];
% % M0img = [];
% M0roi = [ID_folder '/imgs4ASLtbx/sr11308D_M0_ventMask.nii'];
% % M0roi = [ID_folder '/imgs4ASLtbx/sr11308D_M0_WMmask.nii'];
% % M0roi = [];
% maskimg = [ID_folder '/imgs4ASLtbx/sr11308D_M0brainmask.nii'];
% M0csf = [];
% M0wm = [];
% 
% [N_LCpairs, glcbf] = asl_perf_subtract (Filename, ...
%                                           FirstimageType, ...
%                                           SubtractionType, ...
%                                           SubtractionOrder, ...
%                                           Flag, ...
%                                           Timeshift, ...
%                                           AslType, ...
%                                           labeff, ...
%                                           MagType, ...
%                                           Labeltime, ...
%                                           Delaytime, ...
%                                           Slicetime, ...
%                                           TE, ...
%                                           M0img, ...
%                                           M0roi, ...
%                                           maskimg, ...
%                                           M0csf, ...
%                                           M0wm)


% %% - asl_perf_subtract run after generating all necessary imgs
% %   pCASL run
% ASLtbx_path = '/home/jiyang/Dropbox/Jiyang/CNSP/CNS/Perfusion/ASLtbx2_Jmod';
% spm12path = '/usr/share/spm12';
% addpath (ASLtbx_path, spm12path);
% 
% ID_folder = '/data_pub/jiyang/ASL_testing_PASL/subjects/31004';
% 
% Filename = [ID_folder '/imgs4ASLtbx/sASLflt_r31004_PASL.nii'];
% FirstimageType = 1;
% SubtractionType = 0;
% SubtractionOrder = 0;
% 
% % using voxel M0
% fixM0 = 0;
% M0wmcsf2estimateM0b = 1;
% 
% Flag = [1 1 1 1 1 1 fixM0 1 1 M0wmcsf2estimateM0b];
% Timeshift = 0.5;
% AslType = 0;
% labeff = 0.95;
% MagType = 1;
% Labeltime = 0.7;
% Delaytime = 1.8;
% Slicetime = 46.66667;
% TE = 11;
% M0img = [ID_folder '/imgs4ASLtbx/sr31004_M0.nii'];
% % M0img = [];
% % M0roi = [ID_folder '/imgs4ASLtbx/sr31004_M0_ventMask.nii'];
% % M0roi = [ID_folder '/imgs4ASLtbx/sr31004_M0_WMmask.nii'];
% M0roi = [];
% maskimg = [ID_folder '/imgs4ASLtbx/sr31004_M0brainmask.nii'];
% M0csf = [];
% M0wm = [];
% 
% [N_LCpairs, glcbf] = asl_perf_subtract (Filename, ...
%                                           FirstimageType, ...
%                                           SubtractionType, ...
%                                           SubtractionOrder, ...
%                                           Flag, ...
%                                           Timeshift, ...
%                                           AslType, ...
%                                           labeff, ...
%                                           MagType, ...
%                                           Labeltime, ...
%                                           Delaytime, ...
%                                           Slicetime, ...
%                                           TE, ...
%                                           M0img, ...
%                                           M0roi, ...
%                                           maskimg, ...
%                                           M0csf, ...
%                                           M0wm)
              