%% training
createTrainingTblFile (9,...
    '/home/jiyang/MyPipeline_to_fitWanlinOutput_useThis_unnecessaryRemoved',...
    '/home/jiyang/MAS_W4_2016-09-15/subjects',...
    'equalizeYN','0',...              %%% equale YN is likely to cause false positive of large clusters
    '0022', 'Yes', 'No', 'No',...
    '0046', 'Yes', 'No', 'No',...
    '0082', 'Yes', 'No', 'No',...
    '0099', 'Yes', 'No', 'No',...
    '0202', 'Yes', 'No', 'No',...
    '0306', 'Yes', 'No', 'No',...
    '9091', 'Yes', 'No', 'No', ...
    '100307', 'Yes', 'No', 'Yes',...
    '2851', 'No', 'No', 'Yes'...
    );
    
